version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  static_files:
  media_files:
  pg_data:

services:
  db:
    container_name: kudasova-db
    image: postgres:13.10-alpine
    networks:
      - app_network
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: kudasova-backend
    image: vladislavmalygin/kudasova_backend:latest
    networks:
      - app_network
    env_file: .env
    volumes:
      - static_files:/backend_static
      - media_files:/app/media/
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: kudasova-frontend
    image: vladislavmalygin/kudasova_frontend:latest
    networks:
      - app_network
    volumes:
      - static_files:/frontend_static

  nginx:
    container_name: kudasova-proxy
    image: nginx:latest
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      -
