version: '3.8'

volumes:
  static_files:
  media_files:
  pg_data:

services:
  db:
    container_name: kudasova-db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    container_name: kudasova-backend
    image: vladislavmalygin/kudasova_backend:latest
    env_file: .env
