version: '3.8'

volumes:
  static_files:
  media_files:
  pg_data:
  nginx_config:

networks:
  kudasova_network:
    driver: bridge

services:
  db:
    container_name: kudasova-db
    image: postgres:13.10-alpine
    networks:
      - kudasova_network
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    container_name: kudasova-backend
    image: vladislavmalygin/kudasova_backend:latest
    networks:
      - kudasova_network
    env_file: .env
    volumes:
      - static_files:/backend_static
      - media_files:/app/media/
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    container_name: kudasova-frontend
    image: vladislavmalygin/kudasova_frontend:latest
    networks:
      - kudasova_network
    volumes:
      - static_files:/frontend_static
    restart: always

  nginx:
    container_name: kudasova-proxy
    image: nginx:latest
    networks:
      - kudasova_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Read-only mount
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Read-only mount
      - static_files:/staticfiles/
      - media_files:/media/
    depends_on:
      - backend
      - frontend
    restart: always
