version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kudasova_postgres
    environment:
      POSTGRES_DB: kudasova_db
      POSTGRES_USER: kudasova_user
      POSTGRES_PASSWORD: kudasova_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kudasova_user -d kudasova_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kudasova_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: kudasova_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://kudasova_user:kudasova_password@postgres:5432/kudasova_db
      DEBUG: "true"
      SECRET_KEY: django-insecure-dev-key
      ALLOWED_HOSTS: localhost,127.0.0.1,backend,0.0.0.0
      CORS_ALLOWED_ORIGINS: http://localhost:8080,http://frontend:80
      CSRF_TRUSTED_ORIGINS: http://localhost:8080,http://frontend:80
    volumes:
      - ../backend:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "echo 'Ожидаем PostgreSQL...' &&
             sleep 3 &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - kudasova_network

  frontend:
    build:
      context: ../frontend/kudasova
      dockerfile: Dockerfile
    container_name: kudasova_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - kudasova_network

volumes:
  postgres_data:
  backend_media:
  backend_static:

networks:
  kudasova_network:
    driver: bridge